/* Auto-generated by scripts/generate-seo-data.mjs — do not edit manually */
import type { SeoCity } from "@/lib/seo/types";

export const SEO_CITIES: SeoCity[] = [
  {
    "slug": "paris",
    "name": "Paris",
    "country": "France",
    "region": "Europe",
    "lat": 48.8566,
    "lng": 2.3522
  },
  {
    "slug": "london",
    "name": "London",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 51.5074,
    "lng": -0.1278
  },
  {
    "slug": "amsterdam",
    "name": "Amsterdam",
    "country": "Netherlands",
    "region": "Europe",
    "lat": 52.3676,
    "lng": 4.9041
  },
  {
    "slug": "barcelona",
    "name": "Barcelona",
    "country": "Spain",
    "region": "Europe",
    "lat": 41.3851,
    "lng": 2.1734
  },
  {
    "slug": "berlin",
    "name": "Berlin",
    "country": "Germany",
    "region": "Europe",
    "lat": 52.52,
    "lng": 13.405
  },
  {
    "slug": "munich",
    "name": "Munich",
    "country": "Germany",
    "region": "Europe",
    "lat": 48.1351,
    "lng": 11.582
  },
  {
    "slug": "milan",
    "name": "Milan",
    "country": "Italy",
    "region": "Europe",
    "lat": 45.4642,
    "lng": 9.19
  },
  {
    "slug": "rome",
    "name": "Rome",
    "country": "Italy",
    "region": "Europe",
    "lat": 41.9028,
    "lng": 12.4964
  },
  {
    "slug": "brussels",
    "name": "Brussels",
    "country": "Belgium",
    "region": "Europe",
    "lat": 50.8503,
    "lng": 4.3517
  },
  {
    "slug": "copenhagen",
    "name": "Copenhagen",
    "country": "Denmark",
    "region": "Europe",
    "lat": 55.6761,
    "lng": 12.5683
  },
  {
    "slug": "stockholm",
    "name": "Stockholm",
    "country": "Sweden",
    "region": "Europe",
    "lat": 59.3293,
    "lng": 18.0686
  },
  {
    "slug": "oslo",
    "name": "Oslo",
    "country": "Norway",
    "region": "Europe",
    "lat": 59.9139,
    "lng": 10.7522
  },
  {
    "slug": "helsinki",
    "name": "Helsinki",
    "country": "Finland",
    "region": "Europe",
    "lat": 60.1699,
    "lng": 24.9384
  },
  {
    "slug": "dublin",
    "name": "Dublin",
    "country": "Ireland",
    "region": "Europe",
    "lat": 53.3498,
    "lng": -6.2603
  },
  {
    "slug": "lisbon",
    "name": "Lisbon",
    "country": "Portugal",
    "region": "Europe",
    "lat": 38.7223,
    "lng": -9.1393
  },
  {
    "slug": "porto",
    "name": "Porto",
    "country": "Portugal",
    "region": "Europe",
    "lat": 41.1579,
    "lng": -8.6291
  },
  {
    "slug": "madrid",
    "name": "Madrid",
    "country": "Spain",
    "region": "Europe",
    "lat": 40.4168,
    "lng": -3.7038
  },
  {
    "slug": "valencia",
    "name": "Valencia",
    "country": "Spain",
    "region": "Europe",
    "lat": 39.4699,
    "lng": -0.3763
  },
  {
    "slug": "seville",
    "name": "Seville",
    "country": "Spain",
    "region": "Europe",
    "lat": 37.3891,
    "lng": -5.9845
  },
  {
    "slug": "bilbao",
    "name": "Bilbao",
    "country": "Spain",
    "region": "Europe",
    "lat": 43.263,
    "lng": -2.935
  },
  {
    "slug": "lyon",
    "name": "Lyon",
    "country": "France",
    "region": "Europe",
    "lat": 45.764,
    "lng": 4.8357
  },
  {
    "slug": "marseille",
    "name": "Marseille",
    "country": "France",
    "region": "Europe",
    "lat": 43.2965,
    "lng": 5.3698
  },
  {
    "slug": "bordeaux",
    "name": "Bordeaux",
    "country": "France",
    "region": "Europe",
    "lat": 44.8378,
    "lng": -0.5792
  },
  {
    "slug": "toulouse",
    "name": "Toulouse",
    "country": "France",
    "region": "Europe",
    "lat": 43.6047,
    "lng": 1.4442
  },
  {
    "slug": "nice",
    "name": "Nice",
    "country": "France",
    "region": "Europe",
    "lat": 43.7102,
    "lng": 7.262
  },
  {
    "slug": "strasbourg",
    "name": "Strasbourg",
    "country": "France",
    "region": "Europe",
    "lat": 48.5734,
    "lng": 7.7521
  },
  {
    "slug": "lille",
    "name": "Lille",
    "country": "France",
    "region": "Europe",
    "lat": 50.6292,
    "lng": 3.0573
  },
  {
    "slug": "nantes",
    "name": "Nantes",
    "country": "France",
    "region": "Europe",
    "lat": 47.2184,
    "lng": -1.5536
  },
  {
    "slug": "grenoble",
    "name": "Grenoble",
    "country": "France",
    "region": "Europe",
    "lat": 45.1885,
    "lng": 5.7245
  },
  {
    "slug": "montpellier",
    "name": "Montpellier",
    "country": "France",
    "region": "Europe",
    "lat": 43.6108,
    "lng": 3.8767
  },
  {
    "slug": "hamburg",
    "name": "Hamburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 53.5511,
    "lng": 9.9937
  },
  {
    "slug": "cologne",
    "name": "Cologne",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.9375,
    "lng": 6.9603
  },
  {
    "slug": "frankfurt",
    "name": "Frankfurt",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.1109,
    "lng": 8.6821
  },
  {
    "slug": "stuttgart",
    "name": "Stuttgart",
    "country": "Germany",
    "region": "Europe",
    "lat": 48.7758,
    "lng": 9.1829
  },
  {
    "slug": "dresden",
    "name": "Dresden",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.0504,
    "lng": 13.7373
  },
  {
    "slug": "leipzig",
    "name": "Leipzig",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.3397,
    "lng": 12.3731
  },
  {
    "slug": "hanover",
    "name": "Hanover",
    "country": "Germany",
    "region": "Europe",
    "lat": 52.3759,
    "lng": 9.732
  },
  {
    "slug": "nuremberg",
    "name": "Nuremberg",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.4521,
    "lng": 11.0767
  },
  {
    "slug": "vienna",
    "name": "Vienna",
    "country": "Austria",
    "region": "Europe",
    "lat": 48.2082,
    "lng": 16.3738
  },
  {
    "slug": "salzburg",
    "name": "Salzburg",
    "country": "Austria",
    "region": "Europe",
    "lat": 47.8095,
    "lng": 13.055
  },
  {
    "slug": "innsbruck",
    "name": "Innsbruck",
    "country": "Austria",
    "region": "Europe",
    "lat": 47.2692,
    "lng": 11.4041
  },
  {
    "slug": "zurich",
    "name": "Zurich",
    "country": "Switzerland",
    "region": "Europe",
    "lat": 47.3769,
    "lng": 8.5417
  },
  {
    "slug": "geneva",
    "name": "Geneva",
    "country": "Switzerland",
    "region": "Europe",
    "lat": 46.2044,
    "lng": 6.1432
  },
  {
    "slug": "basel",
    "name": "Basel",
    "country": "Switzerland",
    "region": "Europe",
    "lat": 47.5596,
    "lng": 7.5886
  },
  {
    "slug": "bern",
    "name": "Bern",
    "country": "Switzerland",
    "region": "Europe",
    "lat": 46.948,
    "lng": 7.4474
  },
  {
    "slug": "lausanne",
    "name": "Lausanne",
    "country": "Switzerland",
    "region": "Europe",
    "lat": 46.5197,
    "lng": 6.6323
  },
  {
    "slug": "prague",
    "name": "Prague",
    "country": "Czech Republic",
    "region": "Europe",
    "lat": 50.0755,
    "lng": 14.4378
  },
  {
    "slug": "brno",
    "name": "Brno",
    "country": "Czech Republic",
    "region": "Europe",
    "lat": 49.1951,
    "lng": 16.6068
  },
  {
    "slug": "warsaw",
    "name": "Warsaw",
    "country": "Poland",
    "region": "Europe",
    "lat": 52.2297,
    "lng": 21.0122
  },
  {
    "slug": "krakow",
    "name": "Krakow",
    "country": "Poland",
    "region": "Europe",
    "lat": 50.0647,
    "lng": 19.945
  },
  {
    "slug": "gdansk",
    "name": "Gdansk",
    "country": "Poland",
    "region": "Europe",
    "lat": 54.352,
    "lng": 18.6466
  },
  {
    "slug": "wroclaw",
    "name": "Wroclaw",
    "country": "Poland",
    "region": "Europe",
    "lat": 51.1079,
    "lng": 17.0385
  },
  {
    "slug": "budapest",
    "name": "Budapest",
    "country": "Hungary",
    "region": "Europe",
    "lat": 47.4979,
    "lng": 19.0402
  },
  {
    "slug": "bucharest",
    "name": "Bucharest",
    "country": "Romania",
    "region": "Europe",
    "lat": 44.4268,
    "lng": 26.1025
  },
  {
    "slug": "sofia",
    "name": "Sofia",
    "country": "Bulgaria",
    "region": "Europe",
    "lat": 42.6977,
    "lng": 23.3219
  },
  {
    "slug": "athens",
    "name": "Athens",
    "country": "Greece",
    "region": "Europe",
    "lat": 37.9838,
    "lng": 23.7275
  },
  {
    "slug": "thessaloniki",
    "name": "Thessaloniki",
    "country": "Greece",
    "region": "Europe",
    "lat": 40.6401,
    "lng": 22.9444
  },
  {
    "slug": "istanbul",
    "name": "Istanbul",
    "country": "Turkey",
    "region": "Europe",
    "lat": 41.0082,
    "lng": 28.9784
  },
  {
    "slug": "ankara",
    "name": "Ankara",
    "country": "Turkey",
    "region": "Europe",
    "lat": 39.9334,
    "lng": 32.8597
  },
  {
    "slug": "izmir",
    "name": "Izmir",
    "country": "Turkey",
    "region": "Europe",
    "lat": 38.4237,
    "lng": 27.1428
  },
  {
    "slug": "belgrade",
    "name": "Belgrade",
    "country": "Serbia",
    "region": "Europe",
    "lat": 44.7866,
    "lng": 20.4489
  },
  {
    "slug": "zagreb",
    "name": "Zagreb",
    "country": "Croatia",
    "region": "Europe",
    "lat": 45.815,
    "lng": 15.9819
  },
  {
    "slug": "ljubljana",
    "name": "Ljubljana",
    "country": "Slovenia",
    "region": "Europe",
    "lat": 46.0569,
    "lng": 14.5058
  },
  {
    "slug": "bratislava",
    "name": "Bratislava",
    "country": "Slovakia",
    "region": "Europe",
    "lat": 48.1486,
    "lng": 17.1077
  },
  {
    "slug": "tallinn",
    "name": "Tallinn",
    "country": "Estonia",
    "region": "Europe",
    "lat": 59.437,
    "lng": 24.7536
  },
  {
    "slug": "riga",
    "name": "Riga",
    "country": "Latvia",
    "region": "Europe",
    "lat": 56.9496,
    "lng": 24.1052
  },
  {
    "slug": "vilnius",
    "name": "Vilnius",
    "country": "Lithuania",
    "region": "Europe",
    "lat": 54.6872,
    "lng": 25.2797
  },
  {
    "slug": "reykjavik",
    "name": "Reykjavik",
    "country": "Iceland",
    "region": "Europe",
    "lat": 64.1466,
    "lng": -21.9426
  },
  {
    "slug": "edinburgh",
    "name": "Edinburgh",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 55.9533,
    "lng": -3.1883
  },
  {
    "slug": "glasgow",
    "name": "Glasgow",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 55.8642,
    "lng": -4.2518
  },
  {
    "slug": "manchester",
    "name": "Manchester",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 53.4808,
    "lng": -2.2426
  },
  {
    "slug": "birmingham",
    "name": "Birmingham",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 52.4862,
    "lng": -1.8904
  },
  {
    "slug": "leeds",
    "name": "Leeds",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 53.8008,
    "lng": -1.5491
  },
  {
    "slug": "liverpool",
    "name": "Liverpool",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 53.4084,
    "lng": -2.9916
  },
  {
    "slug": "bristol",
    "name": "Bristol",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 51.4545,
    "lng": -2.5879
  },
  {
    "slug": "cambridge",
    "name": "Cambridge",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 52.2053,
    "lng": 0.1218
  },
  {
    "slug": "oxford",
    "name": "Oxford",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 51.752,
    "lng": -1.2577
  },
  {
    "slug": "brighton",
    "name": "Brighton",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 50.8225,
    "lng": -0.1372
  },
  {
    "slug": "cardiff",
    "name": "Cardiff",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 51.4816,
    "lng": -3.1791
  },
  {
    "slug": "belfast",
    "name": "Belfast",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 54.5973,
    "lng": -5.9301
  },
  {
    "slug": "newcastle",
    "name": "Newcastle",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 54.9783,
    "lng": -1.6178
  },
  {
    "slug": "sheffield",
    "name": "Sheffield",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 53.3811,
    "lng": -1.4701
  },
  {
    "slug": "nottingham",
    "name": "Nottingham",
    "country": "United Kingdom",
    "region": "Europe",
    "lat": 52.9548,
    "lng": -1.1581
  },
  {
    "slug": "turin",
    "name": "Turin",
    "country": "Italy",
    "region": "Europe",
    "lat": 45.0703,
    "lng": 7.6869
  },
  {
    "slug": "florence",
    "name": "Florence",
    "country": "Italy",
    "region": "Europe",
    "lat": 43.7696,
    "lng": 11.2558
  },
  {
    "slug": "bologna",
    "name": "Bologna",
    "country": "Italy",
    "region": "Europe",
    "lat": 44.4949,
    "lng": 11.3426
  },
  {
    "slug": "naples",
    "name": "Naples",
    "country": "Italy",
    "region": "Europe",
    "lat": 40.8518,
    "lng": 14.2681
  },
  {
    "slug": "venice",
    "name": "Venice",
    "country": "Italy",
    "region": "Europe",
    "lat": 45.4408,
    "lng": 12.3155
  },
  {
    "slug": "verona",
    "name": "Verona",
    "country": "Italy",
    "region": "Europe",
    "lat": 45.4384,
    "lng": 10.9916
  },
  {
    "slug": "genoa",
    "name": "Genoa",
    "country": "Italy",
    "region": "Europe",
    "lat": 44.4056,
    "lng": 8.9463
  },
  {
    "slug": "palermo",
    "name": "Palermo",
    "country": "Italy",
    "region": "Europe",
    "lat": 38.1157,
    "lng": 13.3615
  },
  {
    "slug": "antwerp",
    "name": "Antwerp",
    "country": "Belgium",
    "region": "Europe",
    "lat": 51.2194,
    "lng": 4.4025
  },
  {
    "slug": "ghent",
    "name": "Ghent",
    "country": "Belgium",
    "region": "Europe",
    "lat": 51.0543,
    "lng": 3.7174
  },
  {
    "slug": "rotterdam",
    "name": "Rotterdam",
    "country": "Netherlands",
    "region": "Europe",
    "lat": 51.9244,
    "lng": 4.4777
  },
  {
    "slug": "utrecht",
    "name": "Utrecht",
    "country": "Netherlands",
    "region": "Europe",
    "lat": 52.0907,
    "lng": 5.1214
  },
  {
    "slug": "the-hague",
    "name": "The Hague",
    "country": "Netherlands",
    "region": "Europe",
    "lat": 52.0705,
    "lng": 4.3007
  },
  {
    "slug": "eindhoven",
    "name": "Eindhoven",
    "country": "Netherlands",
    "region": "Europe",
    "lat": 51.4416,
    "lng": 5.4697
  },
  {
    "slug": "maastricht",
    "name": "Maastricht",
    "country": "Netherlands",
    "region": "Europe",
    "lat": 50.8514,
    "lng": 5.691
  },
  {
    "slug": "luxembourg-city",
    "name": "Luxembourg City",
    "country": "Luxembourg",
    "region": "Europe",
    "lat": 49.6116,
    "lng": 6.1319
  },
  {
    "slug": "malaga",
    "name": "Malaga",
    "country": "Spain",
    "region": "Europe",
    "lat": 36.7213,
    "lng": -4.4214
  },
  {
    "slug": "granada",
    "name": "Granada",
    "country": "Spain",
    "region": "Europe",
    "lat": 37.1773,
    "lng": -3.5986
  },
  {
    "slug": "zaragoza",
    "name": "Zaragoza",
    "country": "Spain",
    "region": "Europe",
    "lat": 41.6488,
    "lng": -0.8891
  },
  {
    "slug": "a-coruna",
    "name": "A Coruna",
    "country": "Spain",
    "region": "Europe",
    "lat": 43.3623,
    "lng": -8.4115
  },
  {
    "slug": "san-sebastian",
    "name": "San Sebastian",
    "country": "Spain",
    "region": "Europe",
    "lat": 43.3183,
    "lng": -1.9812
  },
  {
    "slug": "palma",
    "name": "Palma",
    "country": "Spain",
    "region": "Europe",
    "lat": 39.5696,
    "lng": 2.6502
  },
  {
    "slug": "murcia",
    "name": "Murcia",
    "country": "Spain",
    "region": "Europe",
    "lat": 37.9922,
    "lng": -1.1307
  },
  {
    "slug": "alicante",
    "name": "Alicante",
    "country": "Spain",
    "region": "Europe",
    "lat": 38.3452,
    "lng": -0.481
  },
  {
    "slug": "coimbra",
    "name": "Coimbra",
    "country": "Portugal",
    "region": "Europe",
    "lat": 40.2033,
    "lng": -8.4103
  },
  {
    "slug": "faro",
    "name": "Faro",
    "country": "Portugal",
    "region": "Europe",
    "lat": 37.0194,
    "lng": -7.9304
  },
  {
    "slug": "bergen",
    "name": "Bergen",
    "country": "Norway",
    "region": "Europe",
    "lat": 60.3913,
    "lng": 5.3221
  },
  {
    "slug": "trondheim",
    "name": "Trondheim",
    "country": "Norway",
    "region": "Europe",
    "lat": 63.4305,
    "lng": 10.3951
  },
  {
    "slug": "gothenburg",
    "name": "Gothenburg",
    "country": "Sweden",
    "region": "Europe",
    "lat": 57.7089,
    "lng": 11.9746
  },
  {
    "slug": "malmo",
    "name": "Malmo",
    "country": "Sweden",
    "region": "Europe",
    "lat": 55.605,
    "lng": 13.0038
  },
  {
    "slug": "aarhus",
    "name": "Aarhus",
    "country": "Denmark",
    "region": "Europe",
    "lat": 56.1629,
    "lng": 10.2039
  },
  {
    "slug": "odense",
    "name": "Odense",
    "country": "Denmark",
    "region": "Europe",
    "lat": 55.4038,
    "lng": 10.4024
  },
  {
    "slug": "tampere",
    "name": "Tampere",
    "country": "Finland",
    "region": "Europe",
    "lat": 61.4978,
    "lng": 23.761
  },
  {
    "slug": "turku",
    "name": "Turku",
    "country": "Finland",
    "region": "Europe",
    "lat": 60.4518,
    "lng": 22.2666
  },
  {
    "slug": "poznan",
    "name": "Poznan",
    "country": "Poland",
    "region": "Europe",
    "lat": 52.4064,
    "lng": 16.9252
  },
  {
    "slug": "lodz",
    "name": "Lodz",
    "country": "Poland",
    "region": "Europe",
    "lat": 51.7592,
    "lng": 19.456
  },
  {
    "slug": "katowice",
    "name": "Katowice",
    "country": "Poland",
    "region": "Europe",
    "lat": 50.2649,
    "lng": 19.0238
  },
  {
    "slug": "cluj-napoca",
    "name": "Cluj-Napoca",
    "country": "Romania",
    "region": "Europe",
    "lat": 46.7712,
    "lng": 23.6236
  },
  {
    "slug": "timisoara",
    "name": "Timisoara",
    "country": "Romania",
    "region": "Europe",
    "lat": 45.7489,
    "lng": 21.2087
  },
  {
    "slug": "sibiu",
    "name": "Sibiu",
    "country": "Romania",
    "region": "Europe",
    "lat": 45.7983,
    "lng": 24.1256
  },
  {
    "slug": "split",
    "name": "Split",
    "country": "Croatia",
    "region": "Europe",
    "lat": 43.5081,
    "lng": 16.4402
  },
  {
    "slug": "dubrovnik",
    "name": "Dubrovnik",
    "country": "Croatia",
    "region": "Europe",
    "lat": 42.6507,
    "lng": 18.0944
  },
  {
    "slug": "toulon",
    "name": "Toulon",
    "country": "France",
    "region": "Europe",
    "lat": 43.1242,
    "lng": 5.928
  },
  {
    "slug": "rennes",
    "name": "Rennes",
    "country": "France",
    "region": "Europe",
    "lat": 48.1173,
    "lng": -1.6778
  },
  {
    "slug": "reims",
    "name": "Reims",
    "country": "France",
    "region": "Europe",
    "lat": 49.2583,
    "lng": 4.0317
  },
  {
    "slug": "dijon",
    "name": "Dijon",
    "country": "France",
    "region": "Europe",
    "lat": 47.322,
    "lng": 5.0415
  },
  {
    "slug": "tours",
    "name": "Tours",
    "country": "France",
    "region": "Europe",
    "lat": 47.3941,
    "lng": 0.6848
  },
  {
    "slug": "angers",
    "name": "Angers",
    "country": "France",
    "region": "Europe",
    "lat": 47.4784,
    "lng": -0.5632
  },
  {
    "slug": "metz",
    "name": "Metz",
    "country": "France",
    "region": "Europe",
    "lat": 49.1193,
    "lng": 6.1757
  },
  {
    "slug": "nancy",
    "name": "Nancy",
    "country": "France",
    "region": "Europe",
    "lat": 48.6921,
    "lng": 6.1844
  },
  {
    "slug": "clermont-ferrand",
    "name": "Clermont-Ferrand",
    "country": "France",
    "region": "Europe",
    "lat": 45.7772,
    "lng": 3.087
  },
  {
    "slug": "saint-etienne",
    "name": "Saint-Etienne",
    "country": "France",
    "region": "Europe",
    "lat": 45.4397,
    "lng": 4.3872
  },
  {
    "slug": "perpignan",
    "name": "Perpignan",
    "country": "France",
    "region": "Europe",
    "lat": 42.6887,
    "lng": 2.8948
  },
  {
    "slug": "avignon",
    "name": "Avignon",
    "country": "France",
    "region": "Europe",
    "lat": 43.9493,
    "lng": 4.8055
  },
  {
    "slug": "caen",
    "name": "Caen",
    "country": "France",
    "region": "Europe",
    "lat": 49.1829,
    "lng": -0.3707
  },
  {
    "slug": "rouen",
    "name": "Rouen",
    "country": "France",
    "region": "Europe",
    "lat": 49.4431,
    "lng": 1.0993
  },
  {
    "slug": "le-havre",
    "name": "Le Havre",
    "country": "France",
    "region": "Europe",
    "lat": 49.4944,
    "lng": 0.1079
  },
  {
    "slug": "brest",
    "name": "Brest",
    "country": "France",
    "region": "Europe",
    "lat": 48.3905,
    "lng": -4.486
  },
  {
    "slug": "quimper",
    "name": "Quimper",
    "country": "France",
    "region": "Europe",
    "lat": 47.9975,
    "lng": -4.0979
  },
  {
    "slug": "la-rochelle",
    "name": "La Rochelle",
    "country": "France",
    "region": "Europe",
    "lat": 46.1603,
    "lng": -1.1511
  },
  {
    "slug": "biarritz",
    "name": "Biarritz",
    "country": "France",
    "region": "Europe",
    "lat": 43.4832,
    "lng": -1.5586
  },
  {
    "slug": "chambery",
    "name": "Chambery",
    "country": "France",
    "region": "Europe",
    "lat": 45.5646,
    "lng": 5.9178
  },
  {
    "slug": "annecy",
    "name": "Annecy",
    "country": "France",
    "region": "Europe",
    "lat": 45.8992,
    "lng": 6.1294
  },
  {
    "slug": "freiburg",
    "name": "Freiburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 47.999,
    "lng": 7.8421
  },
  {
    "slug": "karlsruhe",
    "name": "Karlsruhe",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.0069,
    "lng": 8.4037
  },
  {
    "slug": "mannheim",
    "name": "Mannheim",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.4875,
    "lng": 8.466
  },
  {
    "slug": "heidelberg",
    "name": "Heidelberg",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.3988,
    "lng": 8.6724
  },
  {
    "slug": "bonn",
    "name": "Bonn",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.7374,
    "lng": 7.0982
  },
  {
    "slug": "dusseldorf",
    "name": "Dusseldorf",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.2277,
    "lng": 6.7735
  },
  {
    "slug": "dortmund",
    "name": "Dortmund",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.5136,
    "lng": 7.4653
  },
  {
    "slug": "essen",
    "name": "Essen",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.4556,
    "lng": 7.0116
  },
  {
    "slug": "bremen",
    "name": "Bremen",
    "country": "Germany",
    "region": "Europe",
    "lat": 53.0793,
    "lng": 8.8017
  },
  {
    "slug": "kiel",
    "name": "Kiel",
    "country": "Germany",
    "region": "Europe",
    "lat": 54.3233,
    "lng": 10.1228
  },
  {
    "slug": "rostock",
    "name": "Rostock",
    "country": "Germany",
    "region": "Europe",
    "lat": 54.0924,
    "lng": 12.0991
  },
  {
    "slug": "potsdam",
    "name": "Potsdam",
    "country": "Germany",
    "region": "Europe",
    "lat": 52.3906,
    "lng": 13.0645
  },
  {
    "slug": "magdeburg",
    "name": "Magdeburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 52.1205,
    "lng": 11.6276
  },
  {
    "slug": "erfurt",
    "name": "Erfurt",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.9848,
    "lng": 11.0299
  },
  {
    "slug": "mainz",
    "name": "Mainz",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.9929,
    "lng": 8.2473
  },
  {
    "slug": "augsburg",
    "name": "Augsburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 48.3705,
    "lng": 10.8978
  },
  {
    "slug": "regensburg",
    "name": "Regensburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.0134,
    "lng": 12.1016
  },
  {
    "slug": "wurzburg",
    "name": "Wurzburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.7913,
    "lng": 9.9534
  },
  {
    "slug": "trier",
    "name": "Trier",
    "country": "Germany",
    "region": "Europe",
    "lat": 49.7596,
    "lng": 6.6441
  },
  {
    "slug": "koblenz",
    "name": "Koblenz",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.3569,
    "lng": 7.589
  },
  {
    "slug": "aachen",
    "name": "Aachen",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.7753,
    "lng": 6.0839
  },
  {
    "slug": "muenster",
    "name": "Muenster",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.9607,
    "lng": 7.6261
  },
  {
    "slug": "osnabruck",
    "name": "Osnabruck",
    "country": "Germany",
    "region": "Europe",
    "lat": 52.2799,
    "lng": 8.0472
  },
  {
    "slug": "oldenburg",
    "name": "Oldenburg",
    "country": "Germany",
    "region": "Europe",
    "lat": 53.1435,
    "lng": 8.2146
  },
  {
    "slug": "lubeck",
    "name": "Lubeck",
    "country": "Germany",
    "region": "Europe",
    "lat": 53.8655,
    "lng": 10.6866
  },
  {
    "slug": "halle",
    "name": "Halle",
    "country": "Germany",
    "region": "Europe",
    "lat": 51.4969,
    "lng": 11.9688
  },
  {
    "slug": "chemnitz",
    "name": "Chemnitz",
    "country": "Germany",
    "region": "Europe",
    "lat": 50.8278,
    "lng": 12.9214
  },
  {
    "slug": "pisa",
    "name": "Pisa",
    "country": "Italy",
    "region": "Europe",
    "lat": 43.7228,
    "lng": 10.4017
  },
  {
    "slug": "siena",
    "name": "Siena",
    "country": "Italy",
    "region": "Europe",
    "lat": 43.3188,
    "lng": 11.3308
  },
  {
    "slug": "parma",
    "name": "Parma",
    "country": "Italy",
    "region": "Europe",
    "lat": 44.8015,
    "lng": 10.3279
  },
  {
    "slug": "modena",
    "name": "Modena",
    "country": "Italy",
    "region": "Europe",
    "lat": 44.6471,
    "lng": 10.9252
  },
  {
    "slug": "ravenna",
    "name": "Ravenna",
    "country": "Italy",
    "region": "Europe",
    "lat": 44.4184,
    "lng": 12.2035
  },
  {
    "slug": "trieste",
    "name": "Trieste",
    "country": "Italy",
    "region": "Europe",
    "lat": 45.6495,
    "lng": 13.7768
  },
  {
    "slug": "padua",
    "name": "Padua",
    "country": "Italy",
    "region": "Europe",
    "lat": 45.4064,
    "lng": 11.8768
  },
  {
    "slug": "bari",
    "name": "Bari",
    "country": "Italy",
    "region": "Europe",
    "lat": 41.1171,
    "lng": 16.8719
  },
  {
    "slug": "catania",
    "name": "Catania",
    "country": "Italy",
    "region": "Europe",
    "lat": 37.5079,
    "lng": 15.083
  },
  {
    "slug": "cagliari",
    "name": "Cagliari",
    "country": "Italy",
    "region": "Europe",
    "lat": 39.2238,
    "lng": 9.1217
  },
  {
    "slug": "graz",
    "name": "Graz",
    "country": "Austria",
    "region": "Europe",
    "lat": 47.0707,
    "lng": 15.4395
  },
  {
    "slug": "linz",
    "name": "Linz",
    "country": "Austria",
    "region": "Europe",
    "lat": 48.3069,
    "lng": 14.2858
  },
  {
    "slug": "klagenfurt",
    "name": "Klagenfurt",
    "country": "Austria",
    "region": "Europe",
    "lat": 46.6365,
    "lng": 14.3122
  },
  {
    "slug": "debrecen",
    "name": "Debrecen",
    "country": "Hungary",
    "region": "Europe",
    "lat": 47.5316,
    "lng": 21.6273
  },
  {
    "slug": "szeged",
    "name": "Szeged",
    "country": "Hungary",
    "region": "Europe",
    "lat": 46.253,
    "lng": 20.1414
  },
  {
    "slug": "pecs",
    "name": "Pecs",
    "country": "Hungary",
    "region": "Europe",
    "lat": 46.0727,
    "lng": 18.2323
  },
  {
    "slug": "kosice",
    "name": "Kosice",
    "country": "Slovakia",
    "region": "Europe",
    "lat": 48.7164,
    "lng": 21.2611
  },
  {
    "slug": "ostrava",
    "name": "Ostrava",
    "country": "Czech Republic",
    "region": "Europe",
    "lat": 49.8209,
    "lng": 18.2625
  },
  {
    "slug": "plzen",
    "name": "Plzen",
    "country": "Czech Republic",
    "region": "Europe",
    "lat": 49.7384,
    "lng": 13.3736
  },
  {
    "slug": "liberec",
    "name": "Liberec",
    "country": "Czech Republic",
    "region": "Europe",
    "lat": 50.7663,
    "lng": 15.0543
  },
  {
    "slug": "szczecin",
    "name": "Szczecin",
    "country": "Poland",
    "region": "Europe",
    "lat": 53.4285,
    "lng": 14.5528
  },
  {
    "slug": "lublin",
    "name": "Lublin",
    "country": "Poland",
    "region": "Europe",
    "lat": 51.2465,
    "lng": 22.5684
  },
  {
    "slug": "bialystok",
    "name": "Bialystok",
    "country": "Poland",
    "region": "Europe",
    "lat": 53.1325,
    "lng": 23.1688
  },
  {
    "slug": "tartu",
    "name": "Tartu",
    "country": "Estonia",
    "region": "Europe",
    "lat": 58.3776,
    "lng": 26.729
  },
  {
    "slug": "kaunas",
    "name": "Kaunas",
    "country": "Lithuania",
    "region": "Europe",
    "lat": 54.8985,
    "lng": 23.9036
  },
  {
    "slug": "klaipeda",
    "name": "Klaipeda",
    "country": "Lithuania",
    "region": "Europe",
    "lat": 55.7033,
    "lng": 21.1443
  },
  {
    "slug": "liepaja",
    "name": "Liepaja",
    "country": "Latvia",
    "region": "Europe",
    "lat": 56.5047,
    "lng": 21.0108
  },
  {
    "slug": "daugavpils",
    "name": "Daugavpils",
    "country": "Latvia",
    "region": "Europe",
    "lat": 55.8747,
    "lng": 26.5362
  },
  {
    "slug": "new-york",
    "name": "New York",
    "country": "United States",
    "region": "United States",
    "lat": 40.7128,
    "lng": -74.006
  },
  {
    "slug": "los-angeles",
    "name": "Los Angeles",
    "country": "United States",
    "region": "United States",
    "lat": 34.0522,
    "lng": -118.2437
  },
  {
    "slug": "chicago",
    "name": "Chicago",
    "country": "United States",
    "region": "United States",
    "lat": 41.8781,
    "lng": -87.6298
  },
  {
    "slug": "houston",
    "name": "Houston",
    "country": "United States",
    "region": "United States",
    "lat": 29.7604,
    "lng": -95.3698
  },
  {
    "slug": "phoenix",
    "name": "Phoenix",
    "country": "United States",
    "region": "United States",
    "lat": 33.4484,
    "lng": -112.074
  },
  {
    "slug": "philadelphia",
    "name": "Philadelphia",
    "country": "United States",
    "region": "United States",
    "lat": 39.9526,
    "lng": -75.1652
  },
  {
    "slug": "san-antonio",
    "name": "San Antonio",
    "country": "United States",
    "region": "United States",
    "lat": 29.4241,
    "lng": -98.4936
  },
  {
    "slug": "san-diego",
    "name": "San Diego",
    "country": "United States",
    "region": "United States",
    "lat": 32.7157,
    "lng": -117.1611
  },
  {
    "slug": "dallas",
    "name": "Dallas",
    "country": "United States",
    "region": "United States",
    "lat": 32.7767,
    "lng": -96.797
  },
  {
    "slug": "san-jose",
    "name": "San Jose",
    "country": "United States",
    "region": "United States",
    "lat": 37.3382,
    "lng": -121.8863
  },
  {
    "slug": "austin",
    "name": "Austin",
    "country": "United States",
    "region": "United States",
    "lat": 30.2672,
    "lng": -97.7431
  },
  {
    "slug": "jacksonville",
    "name": "Jacksonville",
    "country": "United States",
    "region": "United States",
    "lat": 30.3322,
    "lng": -81.6557
  },
  {
    "slug": "fort-worth",
    "name": "Fort Worth",
    "country": "United States",
    "region": "United States",
    "lat": 32.7555,
    "lng": -97.3308
  },
  {
    "slug": "columbus",
    "name": "Columbus",
    "country": "United States",
    "region": "United States",
    "lat": 39.9612,
    "lng": -82.9988
  },
  {
    "slug": "charlotte",
    "name": "Charlotte",
    "country": "United States",
    "region": "United States",
    "lat": 35.2271,
    "lng": -80.8431
  },
  {
    "slug": "san-francisco",
    "name": "San Francisco",
    "country": "United States",
    "region": "United States",
    "lat": 37.7749,
    "lng": -122.4194
  },
  {
    "slug": "indianapolis",
    "name": "Indianapolis",
    "country": "United States",
    "region": "United States",
    "lat": 39.7684,
    "lng": -86.1581
  },
  {
    "slug": "seattle",
    "name": "Seattle",
    "country": "United States",
    "region": "United States",
    "lat": 47.6062,
    "lng": -122.3321
  },
  {
    "slug": "denver",
    "name": "Denver",
    "country": "United States",
    "region": "United States",
    "lat": 39.7392,
    "lng": -104.9903
  },
  {
    "slug": "washington",
    "name": "Washington",
    "country": "United States",
    "region": "United States",
    "lat": 38.9072,
    "lng": -77.0369
  },
  {
    "slug": "boston",
    "name": "Boston",
    "country": "United States",
    "region": "United States",
    "lat": 42.3601,
    "lng": -71.0589
  },
  {
    "slug": "nashville",
    "name": "Nashville",
    "country": "United States",
    "region": "United States",
    "lat": 36.1627,
    "lng": -86.7816
  },
  {
    "slug": "detroit",
    "name": "Detroit",
    "country": "United States",
    "region": "United States",
    "lat": 42.3314,
    "lng": -83.0458
  },
  {
    "slug": "portland",
    "name": "Portland",
    "country": "United States",
    "region": "United States",
    "lat": 45.5152,
    "lng": -122.6784
  },
  {
    "slug": "las-vegas",
    "name": "Las Vegas",
    "country": "United States",
    "region": "United States",
    "lat": 36.1699,
    "lng": -115.1398
  },
  {
    "slug": "memphis",
    "name": "Memphis",
    "country": "United States",
    "region": "United States",
    "lat": 35.1495,
    "lng": -90.049
  },
  {
    "slug": "louisville",
    "name": "Louisville",
    "country": "United States",
    "region": "United States",
    "lat": 38.2527,
    "lng": -85.7585
  },
  {
    "slug": "baltimore",
    "name": "Baltimore",
    "country": "United States",
    "region": "United States",
    "lat": 39.2904,
    "lng": -76.6122
  },
  {
    "slug": "milwaukee",
    "name": "Milwaukee",
    "country": "United States",
    "region": "United States",
    "lat": 43.0389,
    "lng": -87.9065
  },
  {
    "slug": "albuquerque",
    "name": "Albuquerque",
    "country": "United States",
    "region": "United States",
    "lat": 35.0844,
    "lng": -106.6504
  },
  {
    "slug": "tucson",
    "name": "Tucson",
    "country": "United States",
    "region": "United States",
    "lat": 32.2226,
    "lng": -110.9747
  },
  {
    "slug": "fresno",
    "name": "Fresno",
    "country": "United States",
    "region": "United States",
    "lat": 36.7378,
    "lng": -119.7871
  },
  {
    "slug": "sacramento",
    "name": "Sacramento",
    "country": "United States",
    "region": "United States",
    "lat": 38.5816,
    "lng": -121.4944
  },
  {
    "slug": "atlanta",
    "name": "Atlanta",
    "country": "United States",
    "region": "United States",
    "lat": 33.749,
    "lng": -84.388
  },
  {
    "slug": "miami",
    "name": "Miami",
    "country": "United States",
    "region": "United States",
    "lat": 25.7617,
    "lng": -80.1918
  },
  {
    "slug": "oakland",
    "name": "Oakland",
    "country": "United States",
    "region": "United States",
    "lat": 37.8044,
    "lng": -122.2712
  },
  {
    "slug": "minneapolis",
    "name": "Minneapolis",
    "country": "United States",
    "region": "United States",
    "lat": 44.9778,
    "lng": -93.265
  },
  {
    "slug": "tulsa",
    "name": "Tulsa",
    "country": "United States",
    "region": "United States",
    "lat": 36.154,
    "lng": -95.9928
  },
  {
    "slug": "cleveland",
    "name": "Cleveland",
    "country": "United States",
    "region": "United States",
    "lat": 41.4993,
    "lng": -81.6944
  },
  {
    "slug": "wichita",
    "name": "Wichita",
    "country": "United States",
    "region": "United States",
    "lat": 37.6872,
    "lng": -97.3301
  },
  {
    "slug": "arlington",
    "name": "Arlington",
    "country": "United States",
    "region": "United States",
    "lat": 32.7357,
    "lng": -97.1081
  },
  {
    "slug": "new-orleans",
    "name": "New Orleans",
    "country": "United States",
    "region": "United States",
    "lat": 29.9511,
    "lng": -90.0715
  },
  {
    "slug": "bakersfield",
    "name": "Bakersfield",
    "country": "United States",
    "region": "United States",
    "lat": 35.3733,
    "lng": -119.0187
  },
  {
    "slug": "tampa",
    "name": "Tampa",
    "country": "United States",
    "region": "United States",
    "lat": 27.9506,
    "lng": -82.4572
  },
  {
    "slug": "honolulu",
    "name": "Honolulu",
    "country": "United States",
    "region": "United States",
    "lat": 21.3069,
    "lng": -157.8583
  },
  {
    "slug": "anaheim",
    "name": "Anaheim",
    "country": "United States",
    "region": "United States",
    "lat": 33.8366,
    "lng": -117.9143
  },
  {
    "slug": "santa-ana",
    "name": "Santa Ana",
    "country": "United States",
    "region": "United States",
    "lat": 33.7455,
    "lng": -117.8677
  },
  {
    "slug": "riverside",
    "name": "Riverside",
    "country": "United States",
    "region": "United States",
    "lat": 33.9533,
    "lng": -117.3962
  },
  {
    "slug": "corpus-christi",
    "name": "Corpus Christi",
    "country": "United States",
    "region": "United States",
    "lat": 27.8006,
    "lng": -97.3964
  },
  {
    "slug": "lexington",
    "name": "Lexington",
    "country": "United States",
    "region": "United States",
    "lat": 38.0406,
    "lng": -84.5037
  },
  {
    "slug": "pittsburgh",
    "name": "Pittsburgh",
    "country": "United States",
    "region": "United States",
    "lat": 40.4406,
    "lng": -79.9959
  },
  {
    "slug": "anchorage",
    "name": "Anchorage",
    "country": "United States",
    "region": "United States",
    "lat": 61.2181,
    "lng": -149.9003
  },
  {
    "slug": "stockton",
    "name": "Stockton",
    "country": "United States",
    "region": "United States",
    "lat": 37.9577,
    "lng": -121.2908
  },
  {
    "slug": "cincinnati",
    "name": "Cincinnati",
    "country": "United States",
    "region": "United States",
    "lat": 39.1031,
    "lng": -84.512
  },
  {
    "slug": "st-louis",
    "name": "St. Louis",
    "country": "United States",
    "region": "United States",
    "lat": 38.627,
    "lng": -90.1994
  },
  {
    "slug": "orlando",
    "name": "Orlando",
    "country": "United States",
    "region": "United States",
    "lat": 28.5383,
    "lng": -81.3792
  },
  {
    "slug": "madison",
    "name": "Madison",
    "country": "United States",
    "region": "United States",
    "lat": 43.0731,
    "lng": -89.4012
  },
  {
    "slug": "boise",
    "name": "Boise",
    "country": "United States",
    "region": "United States",
    "lat": 43.615,
    "lng": -116.2023
  },
  {
    "slug": "salt-lake-city",
    "name": "Salt Lake City",
    "country": "United States",
    "region": "United States",
    "lat": 40.7608,
    "lng": -111.891
  },
  {
    "slug": "providence",
    "name": "Providence",
    "country": "United States",
    "region": "United States",
    "lat": 41.824,
    "lng": -71.4128
  },
  {
    "slug": "richmond",
    "name": "Richmond",
    "country": "United States",
    "region": "United States",
    "lat": 37.5407,
    "lng": -77.436
  },
  {
    "slug": "des-moines",
    "name": "Des Moines",
    "country": "United States",
    "region": "United States",
    "lat": 41.5868,
    "lng": -93.625
  },
  {
    "slug": "raleigh",
    "name": "Raleigh",
    "country": "United States",
    "region": "United States",
    "lat": 35.7796,
    "lng": -78.6382
  },
  {
    "slug": "charleston",
    "name": "Charleston",
    "country": "United States",
    "region": "United States",
    "lat": 32.7765,
    "lng": -79.9311
  },
  {
    "slug": "savannah",
    "name": "Savannah",
    "country": "United States",
    "region": "United States",
    "lat": 32.0809,
    "lng": -81.0912
  },
  {
    "slug": "asheville",
    "name": "Asheville",
    "country": "United States",
    "region": "United States",
    "lat": 35.5951,
    "lng": -82.5515
  },
  {
    "slug": "boulder",
    "name": "Boulder",
    "country": "United States",
    "region": "United States",
    "lat": 40.015,
    "lng": -105.2705
  },
  {
    "slug": "colorado-springs",
    "name": "Colorado Springs",
    "country": "United States",
    "region": "United States",
    "lat": 38.8339,
    "lng": -104.8214
  },
  {
    "slug": "santa-fe",
    "name": "Santa Fe",
    "country": "United States",
    "region": "United States",
    "lat": 35.687,
    "lng": -105.9378
  },
  {
    "slug": "santa-barbara",
    "name": "Santa Barbara",
    "country": "United States",
    "region": "United States",
    "lat": 34.4208,
    "lng": -119.6982
  },
  {
    "slug": "monterey",
    "name": "Monterey",
    "country": "United States",
    "region": "United States",
    "lat": 36.6002,
    "lng": -121.8947
  },
  {
    "slug": "san-luis-obispo",
    "name": "San Luis Obispo",
    "country": "United States",
    "region": "United States",
    "lat": 35.2828,
    "lng": -120.6596
  },
  {
    "slug": "santa-cruz",
    "name": "Santa Cruz",
    "country": "United States",
    "region": "United States",
    "lat": 36.9741,
    "lng": -122.0308
  },
  {
    "slug": "eugene",
    "name": "Eugene",
    "country": "United States",
    "region": "United States",
    "lat": 44.0521,
    "lng": -123.0868
  },
  {
    "slug": "bend",
    "name": "Bend",
    "country": "United States",
    "region": "United States",
    "lat": 44.0582,
    "lng": -121.3153
  },
  {
    "slug": "spokane",
    "name": "Spokane",
    "country": "United States",
    "region": "United States",
    "lat": 47.6588,
    "lng": -117.426
  },
  {
    "slug": "tacoma",
    "name": "Tacoma",
    "country": "United States",
    "region": "United States",
    "lat": 47.2529,
    "lng": -122.4443
  },
  {
    "slug": "bellingham",
    "name": "Bellingham",
    "country": "United States",
    "region": "United States",
    "lat": 48.7519,
    "lng": -122.4787
  },
  {
    "slug": "missoula",
    "name": "Missoula",
    "country": "United States",
    "region": "United States",
    "lat": 46.8721,
    "lng": -113.994
  },
  {
    "slug": "billings",
    "name": "Billings",
    "country": "United States",
    "region": "United States",
    "lat": 45.7833,
    "lng": -108.5007
  },
  {
    "slug": "fargo",
    "name": "Fargo",
    "country": "United States",
    "region": "United States",
    "lat": 46.8772,
    "lng": -96.7898
  },
  {
    "slug": "sioux-falls",
    "name": "Sioux Falls",
    "country": "United States",
    "region": "United States",
    "lat": 43.546,
    "lng": -96.7313
  },
  {
    "slug": "omaha",
    "name": "Omaha",
    "country": "United States",
    "region": "United States",
    "lat": 41.2565,
    "lng": -95.9345
  },
  {
    "slug": "kansas-city",
    "name": "Kansas City",
    "country": "United States",
    "region": "United States",
    "lat": 39.0997,
    "lng": -94.5786
  },
  {
    "slug": "st-paul",
    "name": "St. Paul",
    "country": "United States",
    "region": "United States",
    "lat": 44.9537,
    "lng": -93.09
  },
  {
    "slug": "duluth",
    "name": "Duluth",
    "country": "United States",
    "region": "United States",
    "lat": 46.7867,
    "lng": -92.1005
  },
  {
    "slug": "green-bay",
    "name": "Green Bay",
    "country": "United States",
    "region": "United States",
    "lat": 44.5133,
    "lng": -88.0133
  },
  {
    "slug": "grand-rapids",
    "name": "Grand Rapids",
    "country": "United States",
    "region": "United States",
    "lat": 42.9634,
    "lng": -85.6681
  },
  {
    "slug": "ann-arbor",
    "name": "Ann Arbor",
    "country": "United States",
    "region": "United States",
    "lat": 42.2808,
    "lng": -83.743
  },
  {
    "slug": "traverse-city",
    "name": "Traverse City",
    "country": "United States",
    "region": "United States",
    "lat": 44.7631,
    "lng": -85.6206
  },
  {
    "slug": "columbia",
    "name": "Columbia",
    "country": "United States",
    "region": "United States",
    "lat": 34.0007,
    "lng": -81.0348
  },
  {
    "slug": "greenville",
    "name": "Greenville",
    "country": "United States",
    "region": "United States",
    "lat": 34.8526,
    "lng": -82.394
  },
  {
    "slug": "knoxville",
    "name": "Knoxville",
    "country": "United States",
    "region": "United States",
    "lat": 35.9606,
    "lng": -83.9207
  },
  {
    "slug": "chattanooga",
    "name": "Chattanooga",
    "country": "United States",
    "region": "United States",
    "lat": 35.0456,
    "lng": -85.3097
  },
  {
    "slug": "mobile",
    "name": "Mobile",
    "country": "United States",
    "region": "United States",
    "lat": 30.6954,
    "lng": -88.0399
  },
  {
    "slug": "tallahassee",
    "name": "Tallahassee",
    "country": "United States",
    "region": "United States",
    "lat": 30.4383,
    "lng": -84.2807
  },
  {
    "slug": "gainesville",
    "name": "Gainesville",
    "country": "United States",
    "region": "United States",
    "lat": 29.6516,
    "lng": -82.3248
  },
  {
    "slug": "sarasota",
    "name": "Sarasota",
    "country": "United States",
    "region": "United States",
    "lat": 27.3364,
    "lng": -82.5307
  },
  {
    "slug": "fort-lauderdale",
    "name": "Fort Lauderdale",
    "country": "United States",
    "region": "United States",
    "lat": 26.1224,
    "lng": -80.1373
  }
];
