import type { Route } from "@/types/route";

type SeedRoute = Omit<Route, "id">;

const seedData: SeedRoute[] = [
  {
    route_name: "Bologna Circuit",
    world: "Bologna",
    continent: "Europe",
    distance_km: 12.5,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "Bologna Hill Loop",
    world: "Bologna",
    continent: "Europe",
    distance_km: 14,
    elevation_m: 450,
    difficulty: "hard",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["climbing"],
  },
  {
    route_name: "Bologna Time Trial",
    world: "Bologna",
    continent: "Europe",
    distance_km: 8,
    elevation_m: 220,
    difficulty: "hard",
    estimated_time_beginner: 26,
    estimated_time_intermediate: 20,
    estimated_time_advanced: 16,
    estimated_time_competitive: 13,
    training_tags: ["climbing"],
  },
  {
    route_name: "France Champs Loop",
    world: "France",
    continent: "Europe",
    distance_km: 9,
    elevation_m: 50,
    difficulty: "easy",
    estimated_time_beginner: 29,
    estimated_time_intermediate: 22,
    estimated_time_advanced: 18,
    estimated_time_competitive: 15,
    training_tags: ["recovery"],
  },
  {
    route_name: "France Douce France",
    world: "France",
    continent: "Europe",
    distance_km: 23,
    elevation_m: 200,
    difficulty: "easy",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["endurance"],
  },
  {
    route_name: "France Lutece Express",
    world: "France",
    continent: "Europe",
    distance_km: 11,
    elevation_m: 80,
    difficulty: "easy",
    estimated_time_beginner: 37,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 22,
    estimated_time_competitive: 19,
    training_tags: ["endurance"],
  },
  {
    route_name: "France Petit Boucle",
    world: "France",
    continent: "Europe",
    distance_km: 14.5,
    elevation_m: 150,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance"],
  },
  {
    route_name: "France R.G.V.",
    world: "France",
    continent: "Europe",
    distance_km: 12,
    elevation_m: 90,
    difficulty: "easy",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "Grand Tour de France",
    world: "France",
    continent: "Europe",
    distance_km: 87.2,
    elevation_m: 483,
    difficulty: "epic",
    estimated_time_beginner: 240,
    estimated_time_intermediate: 185,
    estimated_time_advanced: 150,
    estimated_time_competitive: 125,
    training_tags: ["challenge", "endurance", "epic"],
  },
  {
    route_name: "Petit Tour de France",
    world: "France",
    continent: "Europe",
    distance_km: 35.2,
    elevation_m: 278,
    difficulty: "moderate",
    estimated_time_beginner: 105,
    estimated_time_intermediate: 80,
    estimated_time_advanced: 65,
    estimated_time_competitive: 54,
    training_tags: ["endurance", "countryside"],
  },
  {
    route_name: "Innsbruck KOM After Party",
    world: "Innsbruck",
    continent: "Europe",
    distance_km: 23.4,
    elevation_m: 489,
    difficulty: "hard",
    estimated_time_beginner: 82,
    estimated_time_intermediate: 62,
    estimated_time_advanced: 50,
    estimated_time_competitive: 42,
    training_tags: ["climbing", "endurance", "alpine"],
  },
  {
    route_name: "Innsbruck KOM Circuit",
    world: "Innsbruck",
    continent: "Europe",
    distance_km: 12,
    elevation_m: 500,
    difficulty: "hard",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["climbing"],
  },
  {
    route_name: "Innsbruck Short Loop",
    world: "Innsbruck",
    continent: "Europe",
    distance_km: 6.5,
    elevation_m: 90,
    difficulty: "easy",
    estimated_time_beginner: 24,
    estimated_time_intermediate: 18,
    estimated_time_advanced: 14,
    estimated_time_competitive: 12,
    training_tags: ["recovery"],
  },
  {
    route_name: "Innsbruckring",
    world: "Innsbruck",
    continent: "Europe",
    distance_km: 8.7,
    elevation_m: 156,
    difficulty: "moderate",
    estimated_time_beginner: 32,
    estimated_time_intermediate: 26,
    estimated_time_advanced: 22,
    estimated_time_competitive: 18,
    training_tags: ["recovery", "alpine"],
  },
  {
    route_name: "Lutscher",
    world: "Innsbruck",
    continent: "Europe",
    distance_km: 13.6,
    elevation_m: 398,
    difficulty: "hard",
    estimated_time_beginner: 58,
    estimated_time_intermediate: 44,
    estimated_time_advanced: 36,
    estimated_time_competitive: 30,
    training_tags: ["climbing", "alpine"],
  },
  {
    route_name: "Greater London Flat",
    world: "London",
    continent: "Europe",
    distance_km: 11.7,
    elevation_m: 53,
    difficulty: "easy",
    estimated_time_beginner: 36,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 23,
    estimated_time_competitive: 19,
    training_tags: ["recovery", "flat", "urban"],
  },
  {
    route_name: "London Classique",
    world: "London",
    continent: "Europe",
    distance_km: 12.3,
    elevation_m: 180,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "London Flat Out",
    world: "London",
    continent: "Europe",
    distance_km: 10,
    elevation_m: 40,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["endurance"],
  },
  {
    route_name: "London Greater Loop",
    world: "London",
    continent: "Europe",
    distance_km: 18,
    elevation_m: 300,
    difficulty: "hard",
    estimated_time_beginner: 59,
    estimated_time_intermediate: 45,
    estimated_time_advanced: 36,
    estimated_time_competitive: 30,
    training_tags: ["endurance", "climbing"],
  },
  {
    route_name: "London Loop",
    world: "London",
    continent: "Europe",
    distance_km: 21.5,
    elevation_m: 166,
    difficulty: "moderate",
    estimated_time_beginner: 68,
    estimated_time_intermediate: 52,
    estimated_time_advanced: 42,
    estimated_time_competitive: 35,
    training_tags: ["endurance", "urban"],
  },
  {
    route_name: "London Triple Loop",
    world: "London",
    continent: "Europe",
    distance_km: 20,
    elevation_m: 400,
    difficulty: "hard",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["climbing"],
  },
  {
    route_name: "Castle to Castle",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 48.3,
    elevation_m: 155,
    difficulty: "moderate",
    estimated_time_beginner: 130,
    estimated_time_intermediate: 100,
    estimated_time_advanced: 82,
    estimated_time_competitive: 68,
    training_tags: ["endurance", "scenic"],
  },
  {
    route_name: "Flatland Loop",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 10.2,
    elevation_m: 33,
    difficulty: "easy",
    estimated_time_beginner: 32,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["recovery", "flat"],
  },
  {
    route_name: "Island Hopper",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 12.9,
    elevation_m: 98,
    difficulty: "easy",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 32,
    estimated_time_advanced: 26,
    estimated_time_competitive: 22,
    training_tags: ["recovery", "scenic"],
  },
  {
    route_name: "Makuri Islands Countryside",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 15,
    elevation_m: 200,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Makuri Islands Mountain Pass",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 18,
    elevation_m: 700,
    difficulty: "hard",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["climbing"],
  },
  {
    route_name: "Makuri Islands River Ride",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 12.5,
    elevation_m: 150,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "Makuri Islands Sprint Loop",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 9,
    elevation_m: 80,
    difficulty: "easy",
    estimated_time_beginner: 29,
    estimated_time_intermediate: 22,
    estimated_time_advanced: 18,
    estimated_time_competitive: 15,
    training_tags: ["intervals"],
  },
  {
    route_name: "Makuri Islands Village Loop",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 10,
    elevation_m: 100,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["endurance"],
  },
  {
    route_name: "Neokallipolos",
    world: "Makuri Islands",
    continent: "Asia",
    distance_km: 42.8,
    elevation_m: 646,
    difficulty: "hard",
    estimated_time_beginner: 115,
    estimated_time_intermediate: 88,
    estimated_time_advanced: 72,
    estimated_time_competitive: 60,
    training_tags: ["climbing", "endurance"],
  },
  {
    route_name: "Flat Route",
    world: "New York",
    continent: "North America",
    distance_km: 9.7,
    elevation_m: 52,
    difficulty: "easy",
    estimated_time_beginner: 32,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["recovery", "flat", "urban"],
  },
  {
    route_name: "Knickerbocker Reverse",
    world: "New York",
    continent: "North America",
    distance_km: 22.6,
    elevation_m: 211,
    difficulty: "moderate",
    estimated_time_beginner: 72,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["endurance", "urban", "rolling"],
  },
  {
    route_name: "New York Central Park Loop",
    world: "New York",
    continent: "North America",
    distance_km: 11.5,
    elevation_m: 200,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "New York Everything Bagel",
    world: "New York",
    continent: "North America",
    distance_km: 17,
    elevation_m: 600,
    difficulty: "hard",
    estimated_time_beginner: 66,
    estimated_time_intermediate: 50,
    estimated_time_advanced: 40,
    estimated_time_competitive: 34,
    training_tags: ["climbing"],
  },
  {
    route_name: "New York Gotham Grind",
    world: "New York",
    continent: "North America",
    distance_km: 14,
    elevation_m: 450,
    difficulty: "hard",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["climbing"],
  },
  {
    route_name: "New York Midtown Loop",
    world: "New York",
    continent: "North America",
    distance_km: 12,
    elevation_m: 220,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "New York Park Perimeter",
    world: "New York",
    continent: "North America",
    distance_km: 9.5,
    elevation_m: 150,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["endurance"],
  },
  {
    route_name: "Champs-Élysées Lap",
    world: "Paris",
    continent: "Europe",
    distance_km: 6.6,
    elevation_m: 43,
    difficulty: "easy",
    estimated_time_beginner: 22,
    estimated_time_intermediate: 18,
    estimated_time_advanced: 14,
    estimated_time_competitive: 12,
    training_tags: ["recovery", "flat", "urban"],
  },
  {
    route_name: "Paris Champs Loop",
    world: "Paris",
    continent: "Europe",
    distance_km: 11,
    elevation_m: 60,
    difficulty: "easy",
    estimated_time_beginner: 37,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 22,
    estimated_time_competitive: 19,
    training_tags: ["endurance"],
  },
  {
    route_name: "Paris Flat Sprint",
    world: "Paris",
    continent: "Europe",
    distance_km: 10,
    elevation_m: 40,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["sprint"],
  },
  {
    route_name: "Paris Montmartre Climb",
    world: "Paris",
    continent: "Europe",
    distance_km: 6,
    elevation_m: 250,
    difficulty: "hard",
    estimated_time_beginner: 24,
    estimated_time_intermediate: 18,
    estimated_time_advanced: 14,
    estimated_time_competitive: 12,
    training_tags: ["climbing"],
  },
  {
    route_name: "Richmond Flat Circuit",
    world: "Richmond",
    continent: "North America",
    distance_km: 10.5,
    elevation_m: 60,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["recovery"],
  },
  {
    route_name: "Richmond Rolling Course",
    world: "Richmond",
    continent: "North America",
    distance_km: 13,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance", "climbing"],
  },
  {
    route_name: "Richmond UCI Circuit",
    world: "Richmond",
    continent: "North America",
    distance_km: 15,
    elevation_m: 180,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Richmond UCI Worlds",
    world: "Richmond",
    continent: "North America",
    distance_km: 16.2,
    elevation_m: 158,
    difficulty: "moderate",
    estimated_time_beginner: 52,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance", "racing"],
  },
  {
    route_name: "Big Flat Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 42.2,
    elevation_m: 91,
    difficulty: "moderate",
    estimated_time_beginner: 120,
    estimated_time_intermediate: 92,
    estimated_time_advanced: 75,
    estimated_time_competitive: 62,
    training_tags: ["endurance", "flat"],
  },
  {
    route_name: "Epic KOM",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 44.4,
    elevation_m: 683,
    difficulty: "epic",
    estimated_time_beginner: 130,
    estimated_time_intermediate: 100,
    estimated_time_advanced: 82,
    estimated_time_competitive: 68,
    training_tags: ["challenge", "climbing", "epic"],
  },
  {
    route_name: "Flat Route",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 10.9,
    elevation_m: 25,
    difficulty: "easy",
    estimated_time_beginner: 35,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 22,
    estimated_time_competitive: 18,
    training_tags: ["recovery", "flat", "short"],
  },
  {
    route_name: "Road to Sky",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 17.9,
    elevation_m: 494,
    difficulty: "hard",
    estimated_time_beginner: 75,
    estimated_time_intermediate: 58,
    estimated_time_advanced: 48,
    estimated_time_competitive: 40,
    training_tags: ["climbing", "climb"],
  },
  {
    route_name: "Tempo Fondo",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 29.4,
    elevation_m: 158,
    difficulty: "moderate",
    estimated_time_beginner: 95,
    estimated_time_intermediate: 72,
    estimated_time_advanced: 58,
    estimated_time_competitive: 48,
    training_tags: ["endurance", "rolling"],
  },
  {
    route_name: "Volcano Climb",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 25.5,
    elevation_m: 352,
    difficulty: "moderate",
    estimated_time_beginner: 85,
    estimated_time_intermediate: 65,
    estimated_time_advanced: 52,
    estimated_time_competitive: 44,
    training_tags: ["climbing", "endurance"],
  },
  {
    route_name: "Volcano Flat",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 12.9,
    elevation_m: 52,
    difficulty: "easy",
    estimated_time_beginner: 38,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["recovery", "flat"],
  },
  {
    route_name: "Waistband",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 13.5,
    elevation_m: 82,
    difficulty: "easy",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 32,
    estimated_time_advanced: 26,
    estimated_time_competitive: 22,
    training_tags: ["recovery", "rolling"],
  },
  {
    route_name: "Watopia Advanced Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 19,
    elevation_m: 700,
    difficulty: "hard",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Adventure Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 25,
    elevation_m: 800,
    difficulty: "hard",
    estimated_time_beginner: 99,
    estimated_time_intermediate: 75,
    estimated_time_advanced: 60,
    estimated_time_competitive: 50,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Base Builder",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 26,
    elevation_m: 500,
    difficulty: "moderate",
    estimated_time_beginner: 99,
    estimated_time_intermediate: 75,
    estimated_time_advanced: 60,
    estimated_time_competitive: 50,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Beginner Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 7.5,
    elevation_m: 40,
    difficulty: "easy",
    estimated_time_beginner: 26,
    estimated_time_intermediate: 20,
    estimated_time_advanced: 16,
    estimated_time_competitive: 13,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Challenge Route",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 24,
    elevation_m: 1000,
    difficulty: "epic",
    estimated_time_beginner: 99,
    estimated_time_intermediate: 75,
    estimated_time_advanced: 60,
    estimated_time_competitive: 50,
    training_tags: ["challenge"],
  },
  {
    route_name: "Watopia Chill Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 10,
    elevation_m: 10,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Climb & Recover",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 19,
    elevation_m: 700,
    difficulty: "hard",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Climb Focus",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 21,
    elevation_m: 1000,
    difficulty: "hard",
    estimated_time_beginner: 86,
    estimated_time_intermediate: 65,
    estimated_time_advanced: 52,
    estimated_time_competitive: 44,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Climb Repeat",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 13,
    elevation_m: 650,
    difficulty: "hard",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Climber's Dream",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 21,
    elevation_m: 900,
    difficulty: "hard",
    estimated_time_beginner: 86,
    estimated_time_intermediate: 65,
    estimated_time_advanced: 52,
    estimated_time_competitive: 44,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Coastal Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 14,
    elevation_m: 120,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Daily Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 15,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Easy Cruise",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 10,
    elevation_m: 20,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Easy Spin",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 7,
    elevation_m: 5,
    difficulty: "easy",
    estimated_time_beginner: 24,
    estimated_time_intermediate: 18,
    estimated_time_advanced: 14,
    estimated_time_competitive: 12,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Endurance Base",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 30,
    elevation_m: 400,
    difficulty: "moderate",
    estimated_time_beginner: 119,
    estimated_time_intermediate: 90,
    estimated_time_advanced: 72,
    estimated_time_competitive: 60,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Endurance Plus",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 28,
    elevation_m: 600,
    difficulty: "moderate",
    estimated_time_beginner: 106,
    estimated_time_intermediate: 80,
    estimated_time_advanced: 64,
    estimated_time_competitive: 54,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Endurance Ride Pro",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 30,
    elevation_m: 800,
    difficulty: "hard",
    estimated_time_beginner: 119,
    estimated_time_intermediate: 90,
    estimated_time_advanced: 72,
    estimated_time_competitive: 60,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Epic Climb",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 22,
    elevation_m: 1200,
    difficulty: "hard",
    estimated_time_beginner: 99,
    estimated_time_intermediate: 75,
    estimated_time_advanced: 60,
    estimated_time_competitive: 50,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Epic Endurance",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 35,
    elevation_m: 900,
    difficulty: "hard",
    estimated_time_beginner: 132,
    estimated_time_intermediate: 100,
    estimated_time_advanced: 80,
    estimated_time_competitive: 67,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Evening Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 13,
    elevation_m: 200,
    difficulty: "moderate",
    estimated_time_beginner: 42,
    estimated_time_intermediate: 32,
    estimated_time_advanced: 26,
    estimated_time_competitive: 21,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Explorer Route",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 22,
    elevation_m: 600,
    difficulty: "hard",
    estimated_time_beginner: 86,
    estimated_time_intermediate: 65,
    estimated_time_advanced: 52,
    estimated_time_competitive: 44,
    training_tags: ["challenge"],
  },
  {
    route_name: "Watopia Fast Flat",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 12,
    elevation_m: 10,
    difficulty: "easy",
    estimated_time_beginner: 37,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 22,
    estimated_time_competitive: 19,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Fatigue Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 20,
    elevation_m: 700,
    difficulty: "hard",
    estimated_time_beginner: 79,
    estimated_time_intermediate: 60,
    estimated_time_advanced: 48,
    estimated_time_competitive: 40,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Figure 8",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 14,
    elevation_m: 180,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Flat Route",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 8,
    elevation_m: 30,
    difficulty: "easy",
    estimated_time_beginner: 26,
    estimated_time_intermediate: 20,
    estimated_time_advanced: 16,
    estimated_time_competitive: 13,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Flat Volcano Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 9.5,
    elevation_m: 60,
    difficulty: "easy",
    estimated_time_beginner: 29,
    estimated_time_intermediate: 22,
    estimated_time_advanced: 18,
    estimated_time_competitive: 15,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Fun Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 12,
    elevation_m: 100,
    difficulty: "easy",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Group Ride Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 16,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Hard Ascent",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 19,
    elevation_m: 1100,
    difficulty: "hard",
    estimated_time_beginner: 79,
    estimated_time_intermediate: 60,
    estimated_time_advanced: 48,
    estimated_time_competitive: 40,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Hill Intervals",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 13,
    elevation_m: 400,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["intervals"],
  },
  {
    route_name: "Watopia Hilly Route",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 10.5,
    elevation_m: 150,
    difficulty: "moderate",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["endurance", "climbing"],
  },
  {
    route_name: "Watopia Jungle Circuit",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 13,
    elevation_m: 220,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Jungle Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 12.5,
    elevation_m: 200,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Long Climb",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 28,
    elevation_m: 1300,
    difficulty: "hard",
    estimated_time_beginner: 112,
    estimated_time_intermediate: 85,
    estimated_time_advanced: 68,
    estimated_time_competitive: 57,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Long Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 25,
    elevation_m: 600,
    difficulty: "hard",
    estimated_time_beginner: 92,
    estimated_time_intermediate: 70,
    estimated_time_advanced: 56,
    estimated_time_competitive: 47,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Long Recovery",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 20,
    elevation_m: 150,
    difficulty: "easy",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Long Steady",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 32,
    elevation_m: 700,
    difficulty: "hard",
    estimated_time_beginner: 125,
    estimated_time_intermediate: 95,
    estimated_time_advanced: 76,
    estimated_time_competitive: 64,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Mixed Terrain",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 17,
    elevation_m: 500,
    difficulty: "moderate",
    estimated_time_beginner: 59,
    estimated_time_intermediate: 45,
    estimated_time_advanced: 36,
    estimated_time_competitive: 30,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Morning Warmup",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 8,
    elevation_m: 60,
    difficulty: "easy",
    estimated_time_beginner: 26,
    estimated_time_intermediate: 20,
    estimated_time_advanced: 16,
    estimated_time_competitive: 13,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Mountain 8",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 20,
    elevation_m: 800,
    difficulty: "hard",
    estimated_time_beginner: 79,
    estimated_time_intermediate: 60,
    estimated_time_advanced: 48,
    estimated_time_competitive: 40,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Mountain Route",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 18,
    elevation_m: 650,
    difficulty: "hard",
    estimated_time_beginner: 66,
    estimated_time_intermediate: 50,
    estimated_time_advanced: 40,
    estimated_time_competitive: 34,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Ocean Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 11.3,
    elevation_m: 90,
    difficulty: "easy",
    estimated_time_beginner: 37,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 22,
    estimated_time_competitive: 19,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Out and Back Again",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 16,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Performance Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 18,
    elevation_m: 450,
    difficulty: "hard",
    estimated_time_beginner: 66,
    estimated_time_intermediate: 50,
    estimated_time_advanced: 40,
    estimated_time_competitive: 34,
    training_tags: ["challenge"],
  },
  {
    route_name: "Watopia Power Climb",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 15,
    elevation_m: 800,
    difficulty: "hard",
    estimated_time_beginner: 59,
    estimated_time_intermediate: 45,
    estimated_time_advanced: 36,
    estimated_time_competitive: 30,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Power Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 18,
    elevation_m: 500,
    difficulty: "hard",
    estimated_time_beginner: 66,
    estimated_time_intermediate: 50,
    estimated_time_advanced: 40,
    estimated_time_competitive: 34,
    training_tags: ["challenge"],
  },
  {
    route_name: "Watopia Race Prep",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 14,
    elevation_m: 350,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["challenge"],
  },
  {
    route_name: "Watopia Race Simulation",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 24,
    elevation_m: 900,
    difficulty: "epic",
    estimated_time_beginner: 92,
    estimated_time_intermediate: 70,
    estimated_time_advanced: 56,
    estimated_time_competitive: 47,
    training_tags: ["challenge"],
  },
  {
    route_name: "Watopia Recovery Flow",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 9,
    elevation_m: 20,
    difficulty: "easy",
    estimated_time_beginner: 29,
    estimated_time_intermediate: 22,
    estimated_time_advanced: 18,
    estimated_time_competitive: 15,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Recovery Ride Plus",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 11,
    elevation_m: 30,
    difficulty: "easy",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Recovery Spin",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 6,
    elevation_m: 5,
    difficulty: "easy",
    estimated_time_beginner: 20,
    estimated_time_intermediate: 15,
    estimated_time_advanced: 12,
    estimated_time_competitive: 10,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Rolling Hills",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 12,
    elevation_m: 180,
    difficulty: "moderate",
    estimated_time_beginner: 40,
    estimated_time_intermediate: 30,
    estimated_time_advanced: 24,
    estimated_time_competitive: 20,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Sand and Sequoias",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 19.5,
    elevation_m: 400,
    difficulty: "hard",
    estimated_time_beginner: 73,
    estimated_time_intermediate: 55,
    estimated_time_advanced: 44,
    estimated_time_competitive: 37,
    training_tags: ["endurance", "climbing"],
  },
  {
    route_name: "Watopia Seaside Sprint",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 7,
    elevation_m: 20,
    difficulty: "easy",
    estimated_time_beginner: 20,
    estimated_time_intermediate: 15,
    estimated_time_advanced: 12,
    estimated_time_competitive: 10,
    training_tags: ["sprint"],
  },
  {
    route_name: "Watopia Short Climb",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 6,
    elevation_m: 200,
    difficulty: "moderate",
    estimated_time_beginner: 24,
    estimated_time_intermediate: 18,
    estimated_time_advanced: 14,
    estimated_time_competitive: 12,
    training_tags: ["climbing"],
  },
  {
    route_name: "Watopia Short Spin",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 5,
    elevation_m: 10,
    difficulty: "easy",
    estimated_time_beginner: 16,
    estimated_time_intermediate: 12,
    estimated_time_advanced: 10,
    estimated_time_competitive: 8,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Social Spin",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 10,
    elevation_m: 100,
    difficulty: "easy",
    estimated_time_beginner: 33,
    estimated_time_intermediate: 25,
    estimated_time_advanced: 20,
    estimated_time_competitive: 17,
    training_tags: ["recovery"],
  },
  {
    route_name: "Watopia Sprint & Spin",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 11,
    elevation_m: 50,
    difficulty: "easy",
    estimated_time_beginner: 37,
    estimated_time_intermediate: 28,
    estimated_time_advanced: 22,
    estimated_time_competitive: 19,
    training_tags: ["sprint"],
  },
  {
    route_name: "Watopia Sprint Factory",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 8,
    elevation_m: 30,
    difficulty: "easy",
    estimated_time_beginner: 24,
    estimated_time_intermediate: 18,
    estimated_time_advanced: 14,
    estimated_time_competitive: 12,
    training_tags: ["sprint"],
  },
  {
    route_name: "Watopia Sprint Training",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 9,
    elevation_m: 50,
    difficulty: "easy",
    estimated_time_beginner: 26,
    estimated_time_intermediate: 20,
    estimated_time_advanced: 16,
    estimated_time_competitive: 13,
    training_tags: ["sprint"],
  },
  {
    route_name: "Watopia Steady Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 16,
    elevation_m: 200,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Sweet Spot Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 15,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 53,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Tempo Builder",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 17,
    elevation_m: 300,
    difficulty: "moderate",
    estimated_time_beginner: 59,
    estimated_time_intermediate: 45,
    estimated_time_advanced: 36,
    estimated_time_competitive: 30,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Tempo Ride",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 18,
    elevation_m: 250,
    difficulty: "moderate",
    estimated_time_beginner: 59,
    estimated_time_intermediate: 45,
    estimated_time_advanced: 36,
    estimated_time_competitive: 30,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Tempus Fugit",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 15,
    elevation_m: 20,
    difficulty: "easy",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Training Loop",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 14,
    elevation_m: 250,
    difficulty: "moderate",
    estimated_time_beginner: 46,
    estimated_time_intermediate: 35,
    estimated_time_advanced: 28,
    estimated_time_competitive: 23,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Volcano Circuit",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 9.2,
    elevation_m: 120,
    difficulty: "moderate",
    estimated_time_beginner: 29,
    estimated_time_intermediate: 22,
    estimated_time_advanced: 18,
    estimated_time_competitive: 15,
    training_tags: ["endurance"],
  },
  {
    route_name: "Watopia Volcano Climb",
    world: "Watopia",
    continent: "Oceania",
    distance_km: 6.8,
    elevation_m: 300,
    difficulty: "hard",
    estimated_time_beginner: 26,
    estimated_time_intermediate: 20,
    estimated_time_advanced: 16,
    estimated_time_competitive: 13,
    training_tags: ["climbing"],
  },
  {
    route_name: "Harrogate Circuit",
    world: "Yorkshire",
    continent: "Europe",
    distance_km: 13.8,
    elevation_m: 246,
    difficulty: "moderate",
    estimated_time_beginner: 52,
    estimated_time_intermediate: 40,
    estimated_time_advanced: 32,
    estimated_time_competitive: 27,
    training_tags: ["climbing", "hills"],
  },
  {
    route_name: "Yorkshire Loop",
    world: "Yorkshire",
    continent: "Europe",
    distance_km: 12.4,
    elevation_m: 204,
    difficulty: "moderate",
    estimated_time_beginner: 48,
    estimated_time_intermediate: 36,
    estimated_time_advanced: 30,
    estimated_time_competitive: 25,
    training_tags: ["endurance", "rolling", "hills"],
  }
];

function slugify(world: string, routeName: string): string {
  return `${world}-${routeName}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const SEED_ROUTES: Route[] = seedData.map((route) => ({
  id: slugify(route.world, route.route_name),
  ...route,
}));

export function getSeedRoutes(): Route[] {
  return SEED_ROUTES;
}
